AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CloudBot Bootstrap Lambda Layer
Resources:
  layername:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.12
      ContentUri: ./
      LayerName: !Ref "AWS::StackName"
      LicenseInfo: String
  layernamelatest:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - ''
        - - '/CloudBot/Layers/'
          - !Join
            - '-'
            - !Slice
              - 0
              - !Sub
                - '${Length}-1'
                - Length: !Len !Split ['-', !Ref 'AWS::StackName']
              - !Split ['-', !Ref 'AWS::StackName']
          - '-latest'
      Value:
        Fn::GetAtt:
          - "layername"
          - "LayerVersionArn"
      Type: String
      Description: "CloudBot Layers Name Latest Version ARN"
