AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CloudBot Bootstrap Lambda Layer
Parameters:
  ARTIFACTSBUCKET:
    Type: String
  S3Key:
    Type: String
Resources:
  layername:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.12
      ContentUri:
        Bucket: !Ref ARTIFACTSBUCKET
        Key: !Ref S3Key
      LayerName: !Join
        - ''
        - - !Select [0, !Split ['-stack', !Ref 'AWS::StackName']]
          - !Select [1, !Split ['-stack', !Ref 'AWS::StackName']]
  layernamelatest:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - ''
        - - !Select [0, !Split ['-stack', !Ref 'AWS::StackName']]
          - !Select [1, !Split ['-stack', !Ref 'AWS::StackName']]
          - "-latest"
      Value:
        Fn::GetAtt:
          - "layername"
          - "LayerVersionArn"
      Type: String
      Description: "CloudBot Layers Name Latest Version ARN"
